spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  springdoc:
    swagger-ui:
      path: /swagger-ui.html